//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDCAS {
    
    
    public partial class GeograpHicalStats {
        
        /// <summary>
        /// ChartContainer2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CDCAS.UserControls.ChartContainer ChartContainer2;
        
        /// <summary>
        /// ChartContainer1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CDCAS.UserControls.ChartContainer ChartContainer1;
        
        /// <summary>
        /// ChartContainer3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CDCAS.UserControls.ChartContainer ChartContainer3;
    }
}
